### ISSUE TITLE
Unimplemented default error handling

### ISSUE THREAD

**Issue by albodelu** [android10/Android-CleanArchitecture-Kotlin#2]
Default error handling was not implemented and I was waiting for your solution.

[This](https://github.com/android10/Android-CleanArchitecture-Kotlin/pull/1) is a possible way to manage it. Feel free to close it but I would appreciate your opinion.

I'm not sure if I am breaking SOLID principles but show loading and error message tasks
are very related, and are repetitive tasks that I prefer to move to the base classes.

Now you can pass lambdas to the base disposable observer and add default error handling.

My app uses nullable views so I improvised a solution with `lateinit` a little strange for me.

**Edit**: I found this related article for Java:
[RxJava2 and Retrofit2 Error Handling on a single place](https://blog.mindorks.com/rxjava2-and-retrofit2-error-handling-on-a-single-place-8daf720d42d6)

**Comment by android10** [comment]
Thanks for the feedback @albodelu. I will close the ticket for now and will take that into consideration.
