### ISSUE TITLE
Question about Movie vs MovieEntity

### ISSUE THREAD

**Issue by carterhudson** [android10/Android-CleanArchitecture-Kotlin#24]
Are these models both part of the domain?

**Comment by android10** [comment]
Movie = Domain
MovieEntity = DataLayer

**Comment by carterhudson** [comment]
It seems rather misleading that the "entities" or "domain" layer is the innermost ring, yet things are suffixed with "entity" in the data layer. Maybe I'm misunderstanding something?

**Comment by VasileUngureanu** [comment]
@carterhudson "Naming is hard" ))

Each layer can have its own models.

**Comment by carterhudson** [comment]
Sure, I get that naming is hard and each layer can have its own models, but what is meant by labeling the domain layer with "entities"? What other entities are being referred to if not those models?

**Comment by jaychang0917** [comment]
IMHO, the current naming conventions is well-known in software engineering field. For example, Room uses `Entity` annotation to annotate a class as a db entity.

**Comment by mochadwi** [comment]
> Sure, I get that naming is hard and each layer can have its own models, but what other entities are being referred to as being part of the domain layer? I see that it includes UseCases, Entities, and Repositories, so I'm trying to find out if there's some concept I'm missing.
> 
> EDIT: I did more searching and found [this](https://github.com/android10/Android-CleanArchitecture/issues/123) on the older, non-kotlin clean repo, so perhaps this answers my question. It does seem to me, however, that since the goal of this project is education, perhaps the naming conventions could be more clear? Perhaps `MovieEntity` could be `MovieData` denoting the data layer, the domain could have the canonical `Movie` or `MovieEntity` and the presentation layer could be `MovieView`? I'm just spitballing, but I'm trying to advocate for adopting clean and I'd like to head off any confusion if and when I have to explain these concepts to others.

This should be the accepted answer. *stackoverflow
