### ISSUE TITLE
Question: Where would you store shared fragments such as a bottom navigation bar?

### ISSUE THREAD

**Issue by avaitla** [android10/Android-CleanArchitecture-Kotlin#43]
Hi Android10,

I enjoyed reading your article (https://fernandocejas.com/2018/05/07/architecting-android-reloaded/), but had a question about sharing fragments and viewmodels. Where would you recommend is best to store common functionality such as a bottom navigation bar fragment?

Thanks,

Anil

**Comment by dmfrey** [comment]
Wouldn't that be a feature as well?  It just happens to interact with other features. Also, move it out to the Navigation component of Jetpack, then it's mostly in configuration.
