### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [android10/Android-CleanArchitecture-Kotlin#5]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by Zhuinden** [comment]
Nah, mockito-kotlin is better, nhaarman is awesome

**Comment by oleksiyp** [comment]
You say so because you compared i.e. tried mockk? Or just because nhaarman is awesome(not sending spam)? 

You should understand, that 1. It's very difficult to get known in the world of mockito domination. 2. I'm writing to very targeted audience 3. I'm not evil at all

**Comment by Zhuinden** [comment]
I recommend writing a Medium article that explains why one should pick your mocking framework over Mockito

**Comment by oleksiyp** [comment]
I plan to write article on translation from Mockito to my framework. Already have a DZone article just describing features http://dzone.com/articles/new-mocking-tool-for-kotlin-an-alternative-to-java

**Comment by oleksiyp** [comment]
Merry Xmas :christmas_tree: :christmas_tree: :christmas_tree: :smiley:

**Comment by Zhuinden** [comment]
@oleksiyp join the discussion https://www.reddit.com/r/androiddev/comments/7m48p0/what_do_you_guys_think_of_this_new_mocking/
