### ISSUE TITLE
Question: Completable/Flowable UseCase

### ISSUE THREAD

**Issue by freaksgit** [android10/Android-CleanArchitecture-Kotlin#65]
I am trying to apply the architecture to ours legacy project, and I've got some difficullties with UseCases variations.

1. How to implement completable UseCase without return value?

2.  How to implement subscription to some events via UseCase? For example, how to implement UseCase which will deliver ConnectivityChange events to presenter? Or how to observe data changes in repository (w.o. using Rx)?

Thanks for nice sample of Clean Architecture project!

**Comment by aldyaz** [comment]
@freaksgit well it was a year ago :D 
for question number 1 : Create another UseCase that return instance of Completable, without `Type` generic (just `Params`)
