### ISSUE TITLE
How to work with multiple base URL Retrofit?

### ISSUE THREAD

**Issue by letruonglamit** [android10/Android-CleanArchitecture-Kotlin#70]

**Comment by Zhuinden** [comment]
Just make multiple instances, 1 per each baseUrl

**Comment by aaghan** [comment]
@Zhuinden @android10 ,
can you please check my [stackoverflow question](https://stackoverflow.com/questions/61489261/retrofit-interceptor-on-different-module-in-feature-based-clean-architecture-and) regarding the interceptor to use, on this sample's pattern?
