### ISSUE TITLE
How to put few call api to usecase ?

### ISSUE THREAD

**Issue by dashika** [android10/Android-CleanArchitecture-Kotlin#98]

**Comment by ruiperes** [comment]
Don't put api calls on usecase. Is responsibility of the repository handle that.

**Comment by dashika** [comment]
But how if the method run only one?

 override suspend fun run(params: None)

**Comment by ruiperes** [comment]
Can provide some code?

**Comment by dashika** [comment]
`class GetMovieDetails
@Inject constructor(private val moviesRepository: MoviesRepository) : UseCase<MovieDetails, Params>() {

    override suspend fun run(params: Params) = moviesRepository.movieDetails(params.id)

    data class Params(val id: Int)
}`

I want to merge these 2 classes to 1, to have options get movie and their detail from one VM :

1) https://github.com/android10/Android-CleanArchitecture-Kotlin/blob/master/app/src/main/kotlin/com/fernandocejas/sample/features/movies/GetMovies.kt

2) https://github.com/android10/Android-CleanArchitecture-Kotlin/blob/master/app/src/main/kotlin/com/fernandocejas/sample/features/movies/GetMovieDetails.kt

**Comment by ruiperes** [comment]
Why don't use the GetMoviesUseCase and change the repository to return a list of MovieDetails? Or create a new use case when first get the list of movies and next get the details of the movies.

**Comment by dashika** [comment]
Could you please provide me sample code of GetMoviesUseCase , because I'm in confuse with 
https://github.com/android10/Android-CleanArchitecture-Kotlin/blob/master/app/src/main/kotlin/com/fernandocejas/sample/core/interactor/UseCase.kt

**Comment by ruiperes** [comment]
Something like this

`class GetAllMovieDetails
@Inject constructor(private val moviesRepository: MoviesRepository) : UseCase<List<MovieDetails>, Params>() {

    override suspend fun run(params: None) : Either<Failure, List<MovieDetails>> {

        val movies = MoviesRepository.movies()

        return movies.map {
            moviesRepository.movieDetails(it.id)
        }
    } 
}`

**Comment by dashika** [comment]
Many thanks, @ruiperes you save my ass  =)

**Comment by ruiperes** [comment]
> Many thanks, @ruiperes you save my ass  =)

No problem

**Comment by Zhuinden** [comment]
I'd just delete BaseUseCase class, you don't really need it tbh
